# Generated by Django 2.2.1 on 2019-08-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=120)),
                ('guest', models.CharField(max_length=120)),
                ('dates', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('summary', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
