# Generated by Django 2.2.1 on 2019-08-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
