# Generated by Django 2.2.1 on 2019-08-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(max_length=20)),
                ('guest', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('notes', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
