# Generated by Django 2.2.1 on 2019-08-16 05:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0004_auto_20190814_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('confirmation_code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('guest', models.CharField(max_length=120)),
                ('check_in', models.DateField(default=datetime.date.today)),
                ('check_out', models.DateField(default=datetime.date.today)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('notes', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
