# Generated by Django 2.2.1 on 2019-08-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20190816_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='status',
            new_name='paid',
        ),
    ]
