# Generated by Django 2.2.1 on 2019-08-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20190816_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='reservations',
            name='limekee_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000),
        ),
    ]
