# Generated by Django 2.2.1 on 2019-08-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_auto_20190819_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=1000),
        ),
    ]
