# Generated by Django 2.2.1 on 2019-08-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservations_total_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='total_due',
        ),
    ]
