# Generated by Django 2.2.1 on 2019-08-27 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_reservations_total_due'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'permissions': [('create_reservation', 'Can create new reservation')]},
        ),
    ]
