# Generated by Django 2.2.1 on 2019-12-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20190827_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='extra_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000),
        ),
    ]
